# zshenv
# this file should contain commands to set the command search path,
# plus other important environment variables; it should not contain
# commands that produce output or assume the shell is attached to
# a tty

export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
export TERM=xterm-256color
