# install zi
if [[ ! -f $HOME/.config/zi/bin/zi.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}ZI%F{220} Initiative Plugin Manager (%F{33}z-shell/zi%F{220})…%f"
  command mkdir -p "$HOME/.config/zi" && command chmod g-rwX "$HOME/.config/zi"
  command git clone https://github.com/z-shell/zi "$HOME/.config/zi/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

declare -A ZI
ZI[HOME_DIR]="$HOME/.config/zi"

source "$HOME/.config/zi/bin/zi.zsh"
autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi
# end of zi install

setopt promptsubst

zinit lucid for \
  OMZL::history.zsh \
  OMZP::last-working-dir

zinit lucid \
  pick"/dev/null" multisrc"{async,pure}.zsh" for \
  sindresorhus/pure

zinit wait lucid for \
  OMZL::clipboard.zsh \
  OMZL::compfix.zsh \
  OMZL::completion.zsh \
  OMZL::correction.zsh \
  OMZL::directories.zsh \
  OMZL::git.zsh \
  OMZL::grep.zsh \
  OMZL::key-bindings.zsh \
  OMZL::spectrum.zsh \
  OMZL::termsupport.zsh \
  OMZP::colored-man-pages \
  OMZP::debian \
  OMZP::fzf \
  OMZP::git \
  OMZP::github \
  OMZP::gitignore \
  OMZP::node \
  OMZP::npm \
  OMZP::nvm \
  OMZP::sudo

zinit wait lucid for \
  atinit"zicompinit; zicdreplay" \
      z-shell/fast-syntax-highlighting \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions \
  as"completion" \
    OMZP::docker/_docker

# You may need to manually set your language environment
export LANG="en_NZ.UTF-8"

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

alias vim='nvim'
alias gs="git status"

alias android-studio='/opt/android-studio/bin/studio.sh'

# added by travis gem
[ -f /home/dinosaur/.travis/travis.sh ] && source /home/dinosaur/.travis/travis.sh

# fzf
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
