# install zinit
if [[ ! -f $HOME/.config/zinit/bin/zinit.zsh ]]; then
  command mkdir -p "$HOME/.config/zinit" && command chmod g-rwX "$HOME/.config/zinit"
  command git clone https://github.com/zdharma/zinit "$HOME/.config/zinit/bin"
fi

declare -A ZINIT
ZINIT[HOME_DIR]="$HOME/.config/zinit"

source "$HOME/.config/zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
# end of zinit install

setopt promptsubst

zinit lucid for \
  OMZL::history.zsh

zinit wait lucid for \
  OMZL::clipboard.zsh \
  OMZL::compfix.zsh \
  OMZL::completion.zsh \
  OMZL::correction.zsh \
  OMZL::directories.zsh \
  OMZL::git.zsh \
  OMZL::grep.zsh \
  OMZL::key-bindings.zsh \
  OMZL::spectrum.zsh \
  OMZL::termsupport.zsh \
  OMZP::colored-man-pages \
  OMZP::debian \
  OMZP::git \
  OMZP::github \
  OMZP::gitignore \
  OMZP::last-working-dir \
  OMZP::node \
  OMZP::npm \
  OMZP::nvm \
  OMZP::sudo

zinit wait lucid for \
  atinit"zicompinit; zicdreplay" \
      zdharma/fast-syntax-highlighting \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions \
  as"completion" \
    OMZP::docker/_docker

zinit lucid \
  pick"/dev/null" multisrc"{async,pure}.zsh" for \
  sindresorhus/pure

# You may need to manually set your language environment
export LANG="en_NZ.UTF-8"

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

alias gs="git status"

alias android-studio='/opt/android-studio/bin/studio.sh'

# added by travis gem
[ -f /home/dinosaur/.travis/travis.sh ] && source /home/dinosaur/.travis/travis.sh
